# Generated by Django 5.1.3 on 2024-11-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_rename_username_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionoption',
            old_name='username',
            new_name='question',
        ),
    ]
